### ISSUE TITLE
Error `DatabaseNotFound` for collection and database requests

### ISSUE THREAD

**Issue by seeforschauer** [tigrisdata/tigrisdb#208]
**Is your feature request related to a problem? Please describe.**

It's a feature request to add details / change the error code to distinguish whether the collection not found or the database not found in:
* `collection` requests (read, update, replace, delete documents) and in the
* `database` requests (list collections, drop, create or update collections)

**Describe the solution you'd like**

Preferably using https://pkg.go.dev/google.golang.org/genproto/googleapis/rpc/status#Status and standardized details. 
https://cloud.google.com/apis/design/errors#error_details 

**Describe alternatives you've considered**

In the current solution the gRPC code `codes.InvalidArgument` hides this details
```
server/services/v1/query_runner.go-123		
     return nil, api.Errorf(codes.InvalidArgument, "database doesn't exists '%s'", dbName)
```
It's not convenient to parse string `"database doesn't exists '%s'"` which would vary from database to database and can be easily changed by developers.

**Additional context**

-

**Comment by ovaistariq** [comment]
The error being returned has been fixed. We will be defining specific error codes that will cover this as well.
